version: '3.7'

services:
  web:
    build:
      context: ./retentionboards_core/app
      dockerfile: Dockerfile.prod
    command: gunicorn retentionboards_core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - main
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - main
  nginx:
    build: retentionboards_core/nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:80
    depends_on:
      - web
    networks:
      - main

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  main:
    driver: bridge