from retentioneering_library.core.utils import init_config
from retentioneering_library.core.simulator import Simulator
from retentioneering_library.core.market_simulator import Simulator as MarketingSimulator

